### ISSUE TITLE
Unresolved reference: dragInfo

### ISSUE THREAD

**Issue by gfoxiii** [dikeboy/compose-launcher#1]
IDE: Android Studio Chipmunk|2021.2.1 Patch 2

when i Run this project,  got some error

```kotlin
SortUtils.kt:69
Unresolved reference: dragInfo
```

**Comment by dikeboy** [comment]
> IDE: Android Studio Chipmunk|2021.2.1 Patch 2
> 
> when i Run this project, got some error
> 
> ```kotlin
> SortUtils.kt:69
> Unresolved reference: dragInfo
> ```

something not push, you can pull and try again  thanks
